export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  BGYS_YONETICISI = 'ROLE_BGYS_YONETICISI',
  RISK_YONETICISI = 'ROLE_RISK_YONETICISI',
  BIRIM_SORUMLUSU = 'ROLE_BIRIM_SORUMLUSU',
}
